world_frame: map
robots:
  - type: UnitInterface
    robot_id: 1
    robot_name: prior_map
    inputs:
      dsg:
        type: FileDsgInput
        dsg_json: $<env ADT4_PRIOR_MAP>/hydra/backend/dsg.json
        force_robot_id: true
      dgraph:
        type: FileDGraphInput
        dgrf_path: $<env ADT4_PRIOR_MAP>/hydra/backend/deformation_graph.dgrf
        include_priors: true
        fix_as_prior: true
        prior_variance: 1.0e-6
  - type: RosUnitInterface
    robot_id: 0
    rate: 10.0
    robot_name: $<var robot_name>
    robot_frame: $<var robot_name>/odom
    inputs:
      dgraph:
        type: RosDGraphInput
      dsg:
        type: RosDsgInput
        subscribe_to_mesh: false
backend:
  type: MultiBackendModule
  add_objects_to_deformation_graph: false
  anchor_robot_id: -1
  optimize_on_lc: true
  enable_node_merging: true
  update_functors:
    agents: {type: UpdateAgentsFunctor}
  initial_align:
    type: LoopClosureInitialAlign
    reference_robot_id: 1
    alignment_gnc_alpha: 0.9
    rot_sigma: 0.1
    trans_sigma: 10.0
  partial_optimizer: {type: ""}
  pgmo:
    run_mode: FULL
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    optimizer:
      type: KimeraRpgoOptimizer
      solver: LM
      gnc: {inlier_probability: 0.7, mu_step: 1.6, max_iterations: 100}
    covariance:
      odom: 1.0e-04
      loop_close: 1.0e-01
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0e-02
      pose_mesh: 1.0e-02
      place_mesh: 1.0e-02
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
