visualizer_frame: $<var robot_name>/map
graph: {type: GraphFromRos}
plugins:
  mesh:
    type: MeshPlugin
    use_color_adaptor: false
    coloring:
      type: SemanticMeshColoring
renderer:
  layer_z_step: 2.0
  collapse_layers: false
  layers:
    2:
      z_offset_scale: 1.0
      visualize: true
      nodes:
        scale: 0.40
        color: {type: LabelColorAdapter}
        alpha: 0.8
        use_sphere: false
      text:
        draw: true
        collapse: true
        adapter: {type: LabelIdTextAdapter}
        height: 0.5
        scale: 0.45
      bounding_boxes: {draw: true, collapse: true, scale: 0.05, edge_scale: 0.05, alpha: 0.9, edge_break_ratio: 0.5}
    4:
      z_offset_scale: 3.0
      visualize: true
      nodes:
        scale: 0.6
        color:
          type: IdColorAdapter
          colormap: {palette: colorbrewer}
        alpha: 0.8
        use_sphere: false
      text: {draw: true, height: 1.25, scale: 1.0}
      edges: {scale: 0.1, alpha: 0.2}
    2p*:
      z_offset_scale: 0.0
      visualize: true
      nodes:
        scale: 0.1
        alpha: 1.0
        use_sphere: true
        color: {type: PartitionColorAdapter}
      edges:
        scale: 0.1
        alpha: 1.0
        color: {type: ""}
      text: {draw_layer: true, height: 0.9, scale: 0.8}
    3p1:
      z_offset_scale: 2.0
      visualize: true
      nodes:
        scale: 0.2
        color:
          type: UniformColorAdapter
          color: [0, 0, 0]
        alpha: 0.9
        use_sphere: true
      text:
        draw: true
        adapter: {type: IdTextAdapter}
        height: 0.5
        scale: 0.45
      edges:
        scale: 0.1
        alpha: 0.8
        color:
          type: UniformColorAdapter
          color: [0, 0, 0]
  interlayer_edges:
    - {from: 3*, to: 2p*, draw: false}
    - {from: 3*, to: 2, use_child_color: true, scale: 0.08, alpha: 0.5}
    - {from: 4, to: 3*, scale: 0.08, alpha: 0.5}
  layer_plugins:
    - layer: 3p1
      plugins:
        - {type: RegionGrowingBoundaryPlugin}
