robots:
  - robot_name: euclid
    type: robot_executor
    robot_type: spot
    body_frame: euclid/base_link
  - robot_name: hamilton
    type: robot_executor
    robot_type: spot
    body_frame: hamilton/base_link
  - robot_name: apollo
    type: robot_executor
    robot_type: spot
    body_frame: apollo/base_link
  - robot_name: hilbert
    type: robot_executor
    robot_type: simulated-spot
    body_frame: hilbert/base_link
  - robot_name: samoyed
    type: phoenix
    robot_type: husky
    body_frame: samoyed/base_link
  - robot_name: gauss
    type: phoenix
    robot_type: husky
    body_frame: gauss/base_link
  - robot_name: pascal
    type: phoenix
    robot_type: husky
    body_frame: pascal/base_link
  - robot_name: lewis
    type: phoenix
    robot_type: husky
    body_frame: lewis/base_link
planners:
  goto_points:
    plugin:
      type: GotoPoints
  language_planner:
    plugin:
      type: LanguagePlanner
      domain_type: Pddl
      pddl_domain_name: RegionObjectRearrangementDomain
      llm_config: ${ADT4_DLS_PKG}/config/${config}/llm_config.yaml
  tsp_planner:
    plugin:
      type: Tsp
      solver: 2opt
  visit_objects_pddl:
    plugin:
      type: Pddl
      domain_name: GotoObjectDomain
  rearrange_objects_pddl:
    plugin:
      type: Pddl
      domain_name: ObjectRearrangementDomain
  region_rearrange_objects_pddl:
    plugin:
      type: Pddl
      domain_name: RegionObjectRearrangementDomain
  multi_robot_pddl:
    plugin:
      type: MultiRobotPddl
      domain_name: RegionObjectRearrangementDomain_MultiRobot_FD_Explore
  multirobot_region_rearrange_objects_pddl:
    plugin:
      type: MultiRobotLlmPddl
      domain_name: RegionObjectRearrangementDomain
