/**:
  ros__parameters:
    odom_frame: $(var robot_name)/odom
    body_frame: $(var robot_name)/body
    output_dir: $(env ADT4_OUTPUT_DIR)/spot_executor
    spot_ip: $(env ADT4_BOSDYN_IP)
    bosdyn_client_username: $(env ADT4_BOSDYN_USERNAME)
    bosdyn_client_password: $(env ADT4_BOSDYN_PASSWORD)
    mid_level_planner_type: identity
    occupancy_inflation_radius: 0.2
    use_cost_map: true
    cost_map_safe_distance: 1.0
    cost_map_nearest_obstacle_cost: 5.0
    lookahead_distance: 50
    use_fake_path_plan: false
    use_fake_spot_interface: false
    use_fake_spot_pose: false
    fake_spot_external_pose: false
    fake_spot_static_pose: false
    fake_spot_x: 0.01
    fake_spot_y: 0.01
    fake_spot_z: 0.01
    fake_spot_yaw: 0.01
    follower_lookahead: 2.1
    goal_tolerance: 1.0
    detector_model_path: $(env ADT4_WS)/weights/yoloe-26m-seg.pt
    spot_interface: sim
    sim_rgb_topic: /$(var robot_name)/$(var robot_name)_zed/rgb/image_rect_color
    detector_confidence: 0.02
    detector_class_synonyms: "{'bag': 'cement bag', 'pipe': 'gray pipe', 'box': 'cement bag'}"
