---
/**:
  ros__parameters:
    odom_frame: $(var robot_name)/odom
    body_frame: $(var robot_name)/base_link
    output_dir: $(env ADT4_OUTPUT_DIR)/spot_executor
    spot_ip: $(env ADT4_BOSDYN_IP)
    bosdyn_client_username: $(env ADT4_BOSDYN_USERNAME)
    bosdyn_client_password: $(env ADT4_BOSDYN_PASSWORD)
    mid_level_planner_type: astar
    occupancy_inflation_radius: 0.2  # meters
    use_cost_map: true
    cost_map_safe_distance: 1.0  # meters
    cost_map_nearest_obstacle_cost: 5.0  # rbf kernel cost at zero distance
    lookahead_distance: 50  # grid
    use_fake_path_plan: false
    use_fake_spot_interface: false
    use_fake_spot_pose: false
    fake_spot_external_pose: false
    fake_spot_static_pose: false
    fake_spot_x: 0.01
    fake_spot_y: 0.01
    fake_spot_z: 0.01
    fake_spot_yaw: 0.01
    follower_lookahead: 2.1
    goal_tolerance: 2.8
    follow_timeout_per_meter: 6.0
    detector_model_path: $(env ADT4_WS)/weights/yoloe-26m-seg.pt
