paths: [khronos, khronos_ros]
robot_id: 0
config_verbosity: 1
map_frame: $<env ADT4_ROBOT_NAME>/map
odom_frame: $<env ADT4_ROBOT_NAME>/odom
robot_frame: $<env ADT4_ROBOT_NAME>/base_link
map_window: {type: spatial, max_radius_m: 14.0}
input:
  type: RosInput
  max_receiver_queue_size: 1
  inputs:
    camera:
      receiver: {type: ClosedSetImageReceiver, queue_size: 30}
      sensor:
        type: camera_info
        min_range: 0.2
        max_range: 5.0
        extrinsics: {type: ros}
active_window:
  type: ActiveWindow
  volumetric_map: {voxels_per_side: 16, voxel_size: 0.1, truncation_distance: 0.3, with_semantics: false}
  projective_integrator:
    semantic_integrator: {type: SingleLabelIntegrator}
    interpolation_method: {type: adaptive, max_depth_difference_m: 0.1}
  min_output_separation: 0.5
  object_detector:
    type: InstanceForwarding
    min_cluster_size: 30
    min_object_volume: 0.01
    max_range: 10.0
    min_range: 0.05
    instance_id: true
    verbosity: 1
  tracker:
    type: MaxIouTracker
    track_by: pixels
    min_semantic_iou: 0.25
    min_cross_iou: 0.1
    temporal_window: 3.0
    min_num_observations: 10
    verbosity: 0
  object_extractor:
    type: MeshObjectExtractor
    verbosity: 0
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.005
    max_object_volume: 100.0
    min_dynamic_displacement: 1
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.5
    min_object_reconstruction_observations: 10
    object_reconstruction_resolution: -0.05
    visualizer_classification: false
    save_object_images: true
    object_image_output_path: $<env ADT4_OUTPUT_DIR>/images
    projective_integrator:
      num_threads: 8
  khronos_sinks:
    - type: ActiveWindowVisualizer
  sinks:
    - type: TsdfOccupancyPublisher
      min_distance: 0.25
      use_relative_height: true
      slice_height: 0.0
      num_slices: 1
frontend:
  type: GraphBuilder
  agent_extractor:
    enabled: true
    image_output_path: $<env ADT4_OUTPUT_DIR>/agents
  subkeyframe_anchor_max_dist_m: 2.0
  enable_mesh_objects: false
  serialize_dsg_mesh: true
  clear_object_meshes: true
  pgmo: {time_horizon: 15.0, d_graph_resolution: 2.5, mesh_resolution: 0.005}
  graph_connector:
    layers:
      - parent_layer: MESH_PLACES
        child_layers:
          - {layer: OBJECTS}
  graph_updater:
    layer_updates:
      OBJECTS:
        prefix: O
        archive_missing: true
        matcher: {type: IoUNodeMatcher, min_same_iou: 0.2, min_cross_iou: 0.5}
  traversability_places:
    type: traversability
    layer: MESH_PLACES
    estimator:
      type: HeightTraversabilityEstimator
      height_below: 0
      height_above: 0.5
      min_confidence: 1.0
      min_traversability: 1.0
      pessimistic: true
    clustering:
      type: RegionGrowingTraversabilityClustering
      max_radius: 4.0
      num_orientation_bins: 20
      use_diagonal_connectivity: false
      min_connection_width_voxels: 2
      fill_enclosed_unknown_max_voxels: 2000
    sinks:
      - type: TraversabilityVisualizer
sub_keyframe:
  enabled: true
  image_output_path: $<env ADT4_OUTPUT_DIR>/subkeyframes
  sensor_name: camera
  gate: {min_translation_m: 0.25, min_rotation_deg: 15.0}
  tf_lookup: {wait_duration_s: 0.1, buffer_size_s: 30.0, max_tries: 5}
  queue_max_size: 30
backend:
  type: BackendModule
  enable_zmq_interface: false
  publish_backend_tf: true
  serialize_dsg_mesh: true
  min_dsg_separation_s: 1
  publish_mesh: true
  min_mesh_separation_s: 10
  change_gate:
    displacement_threshold_m: 0.10
    node_delta_threshold: 25
    max_interval_s: 2.0
    min_separation_s: 0.5
  enable_async_publish: false
  add_places_to_deformation_graph: false
  optimize_on_lc: true
  update_functors:
    agents: {type: UpdateAgentsFunctor}
    objects:
      type: GenericUpdateFunctor
      verbosity: 0
      layer: OBJECTS
      node_matcher: {type: IoUNodeMatcher, min_same_iou: 0.1, min_cross_iou: 0.3}
      merge_proposer:
        strategy: {type: Pairwise}
    traversability: {type: UpdateRegionGrowingTraversabilityFunctor, layer: MESH_PLACES}
  pgmo:
    run_mode: FULL
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    add_initial_prior: true
    optimizer:
      type: KimeraRpgoOptimizer
      solver: LM
      gnc: {inlier_probability: 0.9, mu_step: 1.6, max_iterations: 100}
    covariance:
      odom: 1.0e-02
      loop_close: 5.0e-02
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0e-02
      pose_mesh: 1.0e-02
      place_mesh: 1.0e-02
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
